global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: "sample-agent"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "medical-rag-pod:8002"
        labels:
          app: "sample-agent"

  - job_name: "cadvisor"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "cadvisor:8080"
        labels:
          app: "sample-agent"
          source: "cadvisor"
